name: METAR LFOT update

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Generate METAR RSS
        env:
          CHECKWX_API_KEY: ${{ secrets.CHECKWX_API_KEY }}
        run: python generate_rss.py

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "metar.xml"
          message: "update METAR"
